# Generated by Django 4.2.5 on 2023-10-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
